language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: required
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

services:
  - docker

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: "UMrl1WtulZRJGRipwKF8grda7y7zhk9/OqeJm7CbfZe1kmHkh5rPhBWl0xQe+5QbwsbKpzACtAKTbDHzlnbAHI+Hbu+c2s0517MIpO3ydxmorSHJiE9Jfun7dIPlW+PU/nOQrLrcKWDQ65YuZ8UCSxFfDAgYNfbZMAtiqX7RUauD0YUQGv7Zi1+c9Et0Keh6gtLgemy4W61ilPr6EvAH0SaEoqr3FSID047r6CN6j0efG447xPMV1bqd5s/ZJY4D9/j0+WKCvBKK3Lm1Xr2cMaV6O9sTa77w5ZhkNOTlrE+11u5Tfs53HVtv972T5d6Uvqg1bm7LlKF2FvEj4X0yhZoEiEsynQxZdCfexXB0SOyYc6msXum1TuC1D9TuWmxNEw0gBaeA1c/xAD6hgDva9z2nRDmnlT212wrCrNkNYAEDbYEvo49hSd+6o4feu7t7d3+e0/9dOiVp5QFFKjQXt10T4OUv4+SphSt/TGUAuzHunwPuVFrZiLhIj8fA91/0aWQvYCiLU7oDPv5CpiWdTrJeaFkWR6w2q2YwWIeKTQPK2hOZKW2e/qj3JpUp03pGnRt7JgIAmuWcs3RofHRoKUiHJ7neq2YDHZUM41t8+EsGWtT6D/n1FCfUDCuMNl9JX4/xVpQXX3hNJ8Ve3ayQy3JCA9DtcyPY/9/l0lYfVDE="

deploy:
  - provider: script
    script: mvn dockerfile:push
    on:
      branch: development

env:
  global:
    - secure: "A9b/wb0sh/uvFB3oKLxMiQJu8S9WvOM7AFvRYFZDgvx4ymsdPmHc/zd1RMOAJKt8QLKrSi533Se1KdIVEHrMVzq04K/GQf9Iu1jTjwlqZ9OtKUvunIrCr4lenDjTU3sgiKYosEA2VntwDgoOnaj33HzErmTjFDCLsDZD2q/j2R2e0bGBHtP3RpWKZLHPaoIfCy6vybcx5jIKZsehfvlBuq2O/CmdPwBv3boy0WtxXN5e2QFHHW9OGkO74EEFZV64lzroSI9lF1JwbMP2BDt8mzwTu5wufqbugId0QwHS2yigdyJ+SKPgRB2Nz7gISZiS5dr/gLW/3JSniW8z+23B/VgqB433ZLQy8OO1o92scn/gIL68Ri1qxwXdnFtvLZivb3jToafzp+88WZfW6WX05gYdHNJ/9CkjFxtFmX8sJ8/40GKVuuW1H88jc+i9ywbzAmQctyhfh2kS2D26YIpwnyNndST3cuShV+7KuVzkzl20AefmksalFrLBXl4XELgj+Ul2PE1IVGjXh/4Bhajch24Zd3pn+tnnCasQUKycm1ZLEgWiWW6gMinl/+mKLrWOaxwxuIIzmW86SqUyvW5YE0kK3naAcDjMFYW0lIZmA4lpwfPadmIUrGXQtqO8bIucF9s7KC+Atx7jU+0lCTIBDCcQ26uaPLP3lQxqDSVNVyk="
    # ^^ DOCKER_USERNAME
    - secure: "lLDUiY/EyLQ92Oo0QPi3DIgeldh/fNZpjjpdDyB2UJ673Mfmpansidql2yJp/IEWhtkeFMV1nn9vIxuqI5sR1SNAGNxR4jSm8DWdYuoctJx26MW2bF9kzihJirPDl2QXiaIeaidB6uCrKosK3fxBUP9VU4dpW+vkOiw/9wUD9yx90ezxKMpn5ut13RTIsnAqiBqGMyvXvYpw5sOVaWuFt1UwNecVDuO45HIjYqRq/GvvH0iaupIkKIQa80XIilO0Txq2kxxZfUwAl50tYwvTTuGspy6xcze24G/v8wC10OG1EezVbuiGRfR4hIVkiIHUBz/bLklhLdzd8u2dBEEtMyPcsLtlYbyJopfe8Iu/NXG+CKFbpuujtbH1l2iVwKDCC7ggLRKQdSZVPXEtKOO1ImWh0+na4N4s1AE538TtHezXEw6lzPw+Fg/X1e+XRCpznR0FGGt+yqtgTlzVDwPWYDQ1M51QHsc2l+RUuoJD9VKhFJy3T4ATyxUa+Ql3qm9t1OXCIY1W2Q9q/rN3XEKYdXWqPgc7V2/jFlT/5yo4nq75ncBnL+BX6z1+xzjKjKOTsLqBi+Gugxy/qS9SLF9owbfh6FipBOLlgMTUL/k1FxJWxORxK9b/WQlpB1Q1e3u6t4GVXVffce0nA+3M3SgryIWQakmPQYqH4tj0VjFjo9M="
    # ^^ DOCKER_PASSWORD

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - mvn clean install dockerfile:build sonar:sonar

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
